import { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Personal Notes",
    short_name: "Personal Notes",
    categories: ["notes", "personal notes", "private notes"],
    description: "Personal notes app for private users.",
    display: "standalone",
    display_override: [
      "window-controls-overlay",
      "standalone",
      "fullscreen",
      "minimal-ui",
    ],
    theme_color: "#000",
    background_color: "#000",
    id: "/",
    start_url: "/",
    icons: [
      {
        src: "/icons/icon_128.png",
        sizes: "128x128",
        type: "image/png",
      },
      {
        src: "/icons/icon_144.png",
        sizes: "144x144",
        type: "image/png",
      },
      {
        src: "/icons/icon_192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/icons/icon_512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/icons/maskable_icon_x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon_x384.png",
        sizes: "384x384",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon_x192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon_x128.png",
        sizes: "128x128",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon_x96.png",
        sizes: "96x96",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon_x72.png",
        sizes: "72x72",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon_x48.png",
        sizes: "48x48",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/maskable_icon.png",
        sizes: "928x928",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    screenshots: [
      {
        form_factor: "wide",
        label: "Add Note Page - Dark Mode",
        platform: "windows",
        src: "/screenshots/desktop/dark_add_note.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "wide",
        label: "Profile Page - Dark Mode",
        platform: "windows",
        src: "/screenshots/desktop/dark_profile.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "wide",
        label: "Notes Others Page - Dark Mode",
        platform: "windows",
        src: "/screenshots/desktop/dark_notes_others.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "wide",
        label: "Archived Page - Light Mode",
        platform: "windows",
        src: "/screenshots/desktop/light_archived.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "wide",
        label: "Labels Page - Light Mode",
        platform: "windows",
        src: "/screenshots/desktop/light_labels.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "wide",
        label: "Notes Pinned Page - Light Mode",
        platform: "windows",
        src: "/screenshots/desktop/light_notes_pinned.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "wide",
        label: "Trash Page - Light Mode",
        platform: "windows",
        src: "/screenshots/desktop/light_trash.webp",
        sizes: "1920x1080",
      },
      {
        form_factor: "narrow",
        label: "Add Note Page - Dark Mode",
        platform: "android",
        src: "/screenshots/mobile/dark_add_note.webp",
        sizes: "1081x2146",
      },
      {
        form_factor: "narrow",
        label: "Notes Others Page - Dark Mode",
        platform: "android",
        src: "/screenshots/mobile/dark_notes_others.webp",
        sizes: "1081x2146",
      },
      {
        form_factor: "narrow",
        label: "Profile Page - Light Mode",
        platform: "android",
        src: "/screenshots/mobile/light_profile.webp",
        sizes: "1081x2146",
      },
      {
        form_factor: "narrow",
        label: "Archived Page - Dark Mode",
        platform: "android",
        src: "/screenshots/mobile/dark_archived.webp",
        sizes: "1081x2146",
      },
      {
        form_factor: "narrow",
        label: "Labels Page - Dark Mode",
        platform: "android",
        src: "/screenshots/mobile/dark_labels.webp",
        sizes: "1081x2146",
      },
    ],
  };
}
